//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kola.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kola.Infrastructure.Localization.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ACCEPT.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account Number.
        /// </summary>
        internal static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account Type.
        /// </summary>
        internal static string account_type {
            get {
                return ResourceManager.GetString("account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADD GIFT KARD.
        /// </summary>
        internal static string add_gift_card {
            get {
                return ResourceManager.GetString("add_gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Kash.
        /// </summary>
        internal static string add_kash {
            get {
                return ResourceManager.GetString("add_kash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your address.
        /// </summary>
        internal static string address_error {
            get {
                return ResourceManager.GetString("address_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Airtime.
        /// </summary>
        internal static string airtime {
            get {
                return ResourceManager.GetString("airtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount cannot be empty.
        /// </summary>
        internal static string amount_cannot_be_empty {
            get {
                return ResourceManager.GetString("amount_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter an amount.
        /// </summary>
        internal static string amount_error {
            get {
                return ResourceManager.GetString("amount_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount must be greather than 0.
        /// </summary>
        internal static string amount_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("amount_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Answer.
        /// </summary>
        internal static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your answer.
        /// </summary>
        internal static string answer_error {
            get {
                return ResourceManager.GetString("answer_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kolakash client.
        /// </summary>
        internal static string appli_version_title {
            get {
                return ResourceManager.GetString("appli_version_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARE YOU SURE YOU.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balance.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error occurred, camera not available.
        /// </summary>
        internal static string camera_not_available {
            get {
                return ResourceManager.GetString("camera_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CANCEL.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This field cannot empty.
        /// </summary>
        internal static string cannot_empty {
            get {
                return ResourceManager.GetString("cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change PIN.
        /// </summary>
        internal static string change_pincode {
            get {
                return ResourceManager.GetString("change_pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charity.
        /// </summary>
        internal static string charity {
            get {
                return ResourceManager.GetString("charity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose title.
        /// </summary>
        internal static string choose_title {
            get {
                return ResourceManager.GetString("choose_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cities and Towns.
        /// </summary>
        internal static string cities_and_towns {
            get {
                return ResourceManager.GetString("cities_and_towns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer cities and tows error.
        /// </summary>
        internal static string cities_and_towns_error {
            get {
                return ResourceManager.GetString("cities_and_towns_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à COMMISSION.
        /// </summary>
        internal static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communities.
        /// </summary>
        internal static string communities {
            get {
                return ResourceManager.GetString("communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à communities_error.
        /// </summary>
        internal static string communities_error {
            get {
                return ResourceManager.GetString("communities_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm New PIN.
        /// </summary>
        internal static string confirm_new_pincode {
            get {
                return ResourceManager.GetString("confirm_new_pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm PIN.
        /// </summary>
        internal static string confirm_pin {
            get {
                return ResourceManager.GetString("confirm_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Counties.
        /// </summary>
        internal static string counties {
            get {
                return ResourceManager.GetString("counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer counties.
        /// </summary>
        internal static string counties_error {
            get {
                return ResourceManager.GetString("counties_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your country.
        /// </summary>
        internal static string country_error {
            get {
                return ResourceManager.GetString("country_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your country identity document.
        /// </summary>
        internal static string country_identity_document_error {
            get {
                return ResourceManager.GetString("country_identity_document_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country of the Identity document.
        /// </summary>
        internal static string county_of_identity_document {
            get {
                return ResourceManager.GetString("county_of_identity_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Gift Kard.
        /// </summary>
        internal static string create_gift_card {
            get {
                return ResourceManager.GetString("create_gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à District.
        /// </summary>
        internal static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer district.
        /// </summary>
        internal static string district_error {
            get {
                return ResourceManager.GetString("district_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want .
        /// </summary>
        internal static string do_you_want {
            get {
                return ResourceManager.GetString("do_you_want", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DONATE.
        /// </summary>
        internal static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t have an account ?.
        /// </summary>
        internal static string dont_have_an_account {
            get {
                return ResourceManager.GetString("dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à e-money services.
        /// </summary>
        internal static string e_money_services {
            get {
                return ResourceManager.GetString("e_money_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Electricity.
        /// </summary>
        internal static string electricity {
            get {
                return ResourceManager.GetString("electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a valid email.
        /// </summary>
        internal static string email_error {
            get {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enrollment fail.
        /// </summary>
        internal static string enrollment_failed {
            get {
                return ResourceManager.GetString("enrollment_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful enrollment.
        /// </summary>
        internal static string enrollment_successfully {
            get {
                return ResourceManager.GetString("enrollment_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Gift Card number.
        /// </summary>
        internal static string enter_gift_card_number {
            get {
                return ResourceManager.GetString("enter_gift_card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your PIN.
        /// </summary>
        internal static string enter_pincode {
            get {
                return ResourceManager.GetString("enter_pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Pin Code.
        /// </summary>
        internal static string enter_your_pin_code {
            get {
                return ResourceManager.GetString("enter_your_pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, please contact the support or retry again later !.
        /// </summary>
        internal static string error_contact_support {
            get {
                return ResourceManager.GetString("error_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, please contact the support or try again later..
        /// </summary>
        internal static string error_occured {
            get {
                return ResourceManager.GetString("error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error occurred while loading the application, please restart it or contact administrator.
        /// </summary>
        internal static string error_occured_application_loading {
            get {
                return ResourceManager.GetString("error_occured_application_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration Date.
        /// </summary>
        internal static string expiration_date {
            get {
                return ResourceManager.GetString("expiration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The expiration date must be greater than or equal to the current date.
        /// </summary>
        internal static string expiration_date_error {
            get {
                return ResourceManager.GetString("expiration_date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The expiration date must be greater than the issue date.
        /// </summary>
        internal static string expiration_issue_date_error {
            get {
                return ResourceManager.GetString("expiration_issue_date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à failed PIN change.
        /// </summary>
        internal static string failed_pincode_change {
            get {
                return ResourceManager.GetString("failed_pincode_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorites.
        /// </summary>
        internal static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à finger print.
        /// </summary>
        internal static string finger_print {
            get {
                return ResourceManager.GetString("finger_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fingerprint actived.
        /// </summary>
        internal static string fingerprint_actived {
            get {
                return ResourceManager.GetString("fingerprint_actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fingerprint deactivated.
        /// </summary>
        internal static string fingerprint_deactivated {
            get {
                return ResourceManager.GetString("fingerprint_deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable fingerprint.
        /// </summary>
        internal static string fingerprint_enabled {
            get {
                return ResourceManager.GetString("fingerprint_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I connect to the application using my fingerprint thanks to the functionality offered by my smartphone.
        /// </summary>
        internal static string fingerprint_help_desc_1 {
            get {
                return ResourceManager.GetString("fingerprint_help_desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à once the feature is activated on my smartphone, I can activate the fingerprint on my application to once The feature is activated on my smartphone, I can activate the fingerprint on my application to connect.
        /// </summary>
        internal static string fingerprint_help_desc_2 {
            get {
                return ResourceManager.GetString("fingerprint_help_desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To activate fingerprint recognition, I must first activate the fingerprint functionality on my smartphone to do this, go to the *Settings* section of my smartphone, then to *Biometric data*.
        /// </summary>
        internal static string fingerprint_help_for_actived {
            get {
                return ResourceManager.GetString("fingerprint_help_for_actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fingerprint Manager.
        /// </summary>
        internal static string fingerprint_manager {
            get {
                return ResourceManager.GetString("fingerprint_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your first name.
        /// </summary>
        internal static string firstname_error {
            get {
                return ResourceManager.GetString("firstname_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot your Pin Code?.
        /// </summary>
        internal static string forgot_your_pin_code {
            get {
                return ResourceManager.GetString("forgot_your_pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a gender.
        /// </summary>
        internal static string gender_error {
            get {
                return ResourceManager.GetString("gender_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gift Kard.
        /// </summary>
        internal static string gift_card {
            get {
                return ResourceManager.GetString("gift_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Gift kard number.
        /// </summary>
        internal static string gift_card_cannot_be_empty {
            get {
                return ResourceManager.GetString("gift_card_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gift kard number is short.
        /// </summary>
        internal static string gift_card_is_short {
            get {
                return ResourceManager.GetString("gift_card_is_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See Qrcode Gift kard.
        /// </summary>
        internal static string gift_card_view_qrcode {
            get {
                return ResourceManager.GetString("gift_card_view_qrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Gift Kards.
        /// </summary>
        internal static string gift_cards {
            get {
                return ResourceManager.GetString("gift_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your gift kard number.
        /// </summary>
        internal static string gitf_card_number_error {
            get {
                return ResourceManager.GetString("gitf_card_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gol.
        /// </summary>
        internal static string gol {
            get {
                return ResourceManager.GetString("gol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID number.
        /// </summary>
        internal static string id_number {
            get {
                return ResourceManager.GetString("id_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID to redeem.
        /// </summary>
        internal static string id_to_redeem {
            get {
                return ResourceManager.GetString("id_to_redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID type.
        /// </summary>
        internal static string id_type {
            get {
                return ResourceManager.GetString("id_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your identity number.
        /// </summary>
        internal static string identity_document_number_error {
            get {
                return ResourceManager.GetString("identity_document_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your identity document type.
        /// </summary>
        internal static string identity_document_type_error {
            get {
                return ResourceManager.GetString("identity_document_type_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insurance.
        /// </summary>
        internal static string insurance {
            get {
                return ResourceManager.GetString("insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Issue Date.
        /// </summary>
        internal static string issue_date {
            get {
                return ResourceManager.GetString("issue_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The issue date must be less than or equal to the current date.
        /// </summary>
        internal static string issue_date_error {
            get {
                return ResourceManager.GetString("issue_date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kash.
        /// </summary>
        internal static string kash {
            get {
                return ResourceManager.GetString("kash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kola Pay.
        /// </summary>
        internal static string kola_pay {
            get {
                return ResourceManager.GetString("kola_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (DSTV, City taxes, etc).
        /// </summary>
        internal static string kola_pay_desc {
            get {
                return ResourceManager.GetString("kola_pay_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kola&apos;s registered number.
        /// </summary>
        internal static string kola_registered_number {
            get {
                return ResourceManager.GetString("kola_registered_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your last name.
        /// </summary>
        internal static string lastname_error {
            get {
                return ResourceManager.GetString("lastname_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading, please wait....
        /// </summary>
        internal static string loading_please_wait {
            get {
                return ResourceManager.GetString("loading_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        internal static string login_welcome {
            get {
                return ResourceManager.GetString("login_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LOGOUT.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make Payment.
        /// </summary>
        internal static string make_payment {
            get {
                return ResourceManager.GetString("make_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage finger print connexion.
        /// </summary>
        internal static string manage_finger_print_connexion {
            get {
                return ResourceManager.GetString("manage_finger_print_connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual payment.
        /// </summary>
        internal static string manual_payment {
            get {
                return ResourceManager.GetString("manual_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchant.
        /// </summary>
        internal static string merchant {
            get {
                return ResourceManager.GetString("merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter merchant id.
        /// </summary>
        internal static string merchant_error {
            get {
                return ResourceManager.GetString("merchant_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchant id.
        /// </summary>
        internal static string merchant_id {
            get {
                return ResourceManager.GetString("merchant_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchant name.
        /// </summary>
        internal static string merchant_name {
            get {
                return ResourceManager.GetString("merchant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchant Payment.
        /// </summary>
        internal static string merchant_payment {
            get {
                return ResourceManager.GetString("merchant_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MTCN.
        /// </summary>
        internal static string mtcn {
            get {
                return ResourceManager.GetString("mtcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Account.
        /// </summary>
        internal static string my_account {
            get {
                return ResourceManager.GetString("my_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Donations.
        /// </summary>
        internal static string my_donations {
            get {
                return ResourceManager.GetString("my_donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Kola krew.
        /// </summary>
        internal static string my_kola_krew {
            get {
                return ResourceManager.GetString("my_kola_krew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Statements.
        /// </summary>
        internal static string my_statements {
            get {
                return ResourceManager.GetString("my_statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Vouchers.
        /// </summary>
        internal static string my_vouchers {
            get {
                return ResourceManager.GetString("my_vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network available, you can continue ....
        /// </summary>
        internal static string network_available {
            get {
                return ResourceManager.GetString("network_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network limited, please check your connection !.
        /// </summary>
        internal static string network_limited {
            get {
                return ResourceManager.GetString("network_limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network unavailable, please check your network !.
        /// </summary>
        internal static string network_unavailable {
            get {
                return ResourceManager.GetString("network_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error occurred, please check your connection !.
        /// </summary>
        internal static string network_unavailable_token {
            get {
                return ResourceManager.GetString("network_unavailable_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New PIN.
        /// </summary>
        internal static string new_pincode {
            get {
                return ResourceManager.GetString("new_pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN does not match with new PIN.
        /// </summary>
        internal static string new_pincode_no_match {
            get {
                return ResourceManager.GetString("new_pincode_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NO.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old PIN.
        /// </summary>
        internal static string old_pincode {
            get {
                return ResourceManager.GetString("old_pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New PIN must be different to current PIN.
        /// </summary>
        internal static string old_pincode_newpincode_cannot_equal {
            get {
                return ResourceManager.GetString("old_pincode_newpincode_cannot_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN is not current PIN.
        /// </summary>
        internal static string oldpincode_is_incorrect {
            get {
                return ResourceManager.GetString("oldpincode_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à on.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation failed.
        /// </summary>
        internal static string operation_failed {
            get {
                return ResourceManager.GetString("operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation was successfull.
        /// </summary>
        internal static string operation_successfully {
            get {
                return ResourceManager.GetString("operation_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your organisation.
        /// </summary>
        internal static string organisation_error {
            get {
                return ResourceManager.GetString("organisation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organizations.
        /// </summary>
        internal static string organizations {
            get {
                return ResourceManager.GetString("organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Others.
        /// </summary>
        internal static string others {
            get {
                return ResourceManager.GetString("others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payments.
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a valid phone number.
        /// </summary>
        internal static string phone_number_error {
            get {
                return ResourceManager.GetString("phone_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number is short.
        /// </summary>
        internal static string phone_number_is_short {
            get {
                return ResourceManager.GetString("phone_number_is_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ACCOUNT.
        /// </summary>
        internal static string piker_wallet_account {
            get {
                return ResourceManager.GetString("piker_wallet_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN.
        /// </summary>
        internal static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN cannot empty.
        /// </summary>
        internal static string pincode_cannot_empty {
            get {
                return ResourceManager.GetString("pincode_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN changed successfully.
        /// </summary>
        internal static string pincode_changed_successfully {
            get {
                return ResourceManager.GetString("pincode_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter PIN.
        /// </summary>
        internal static string pincode_error {
            get {
                return ResourceManager.GetString("pincode_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN is incorrect.
        /// </summary>
        internal static string pincode_is_incorrect {
            get {
                return ResourceManager.GetString("pincode_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN is short.
        /// </summary>
        internal static string pincode_is_short {
            get {
                return ResourceManager.GetString("pincode_is_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIN no match.
        /// </summary>
        internal static string pincode_no_match {
            get {
                return ResourceManager.GetString("pincode_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identify yourself with your fingerprint.
        /// </summary>
        internal static string proove_you_have_finger {
            get {
                return ResourceManager.GetString("proove_you_have_finger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merchant.
        /// </summary>
        internal static string qr_payment {
            get {
                return ResourceManager.GetString("qr_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error occurred while generating the QRCode, please try again later or contact support.
        /// </summary>
        internal static string qrcode_error_occured {
            get {
                return ResourceManager.GetString("qrcode_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The scanned QrCode is not yours!.
        /// </summary>
        internal static string qrcode_is_not_yours {
            get {
                return ResourceManager.GetString("qrcode_is_not_yours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à QrCode not reconized.
        /// </summary>
        internal static string qrcode_not_reconize {
            get {
                return ResourceManager.GetString("qrcode_not_reconize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The detected QRcode does not correspond to your operation.
        /// </summary>
        internal static string qrcode_scan_error_occured {
            get {
                return ResourceManager.GetString("qrcode_scan_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your question.
        /// </summary>
        internal static string question_securuty_error {
            get {
                return ResourceManager.GetString("question_securuty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receiver Phone.
        /// </summary>
        internal static string receiver_phone {
            get {
                return ResourceManager.GetString("receiver_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refer a friend.
        /// </summary>
        internal static string refer_a_friend {
            get {
                return ResourceManager.GetString("refer_a_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REGISTER A VOUCHER.
        /// </summary>
        internal static string register_a_voucher {
            get {
                return ResourceManager.GetString("register_a_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REJECT.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rememeber Me.
        /// </summary>
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan me.
        /// </summary>
        internal static string scan_me {
            get {
                return ResourceManager.GetString("scan_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan merchant QR Code.
        /// </summary>
        internal static string scan_merchant_qr_code {
            get {
                return ResourceManager.GetString("scan_merchant_qr_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan or use.
        /// </summary>
        internal static string scan_or_use {
            get {
                return ResourceManager.GetString("scan_or_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security questions.
        /// </summary>
        internal static string security_questions {
            get {
                return ResourceManager.GetString("security_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEE.
        /// </summary>
        internal static string see {
            get {
                return ResourceManager.GetString("see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Account.
        /// </summary>
        internal static string select_account {
            get {
                return ResourceManager.GetString("select_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Bank.
        /// </summary>
        internal static string select_bank {
            get {
                return ResourceManager.GetString("select_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select cities and towns.
        /// </summary>
        internal static string select_cities_and_towns {
            get {
                return ResourceManager.GetString("select_cities_and_towns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select city.
        /// </summary>
        internal static string select_city {
            get {
                return ResourceManager.GetString("select_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select communities.
        /// </summary>
        internal static string select_communities {
            get {
                return ResourceManager.GetString("select_communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select counties.
        /// </summary>
        internal static string select_counties {
            get {
                return ResourceManager.GetString("select_counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select country.
        /// </summary>
        internal static string select_country {
            get {
                return ResourceManager.GetString("select_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Currency.
        /// </summary>
        internal static string select_currency {
            get {
                return ResourceManager.GetString("select_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select district.
        /// </summary>
        internal static string select_district {
            get {
                return ResourceManager.GetString("select_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select identity document.
        /// </summary>
        internal static string select_identity_document {
            get {
                return ResourceManager.GetString("select_identity_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select identity type.
        /// </summary>
        internal static string select_identity_type {
            get {
                return ResourceManager.GetString("select_identity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Merchant.
        /// </summary>
        internal static string select_merchant {
            get {
                return ResourceManager.GetString("select_merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select neighborhood.
        /// </summary>
        internal static string select_neighborhood {
            get {
                return ResourceManager.GetString("select_neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Organization.
        /// </summary>
        internal static string select_organization {
            get {
                return ResourceManager.GetString("select_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select security question.
        /// </summary>
        internal static string select_security_question {
            get {
                return ResourceManager.GetString("select_security_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send money to bank account.
        /// </summary>
        internal static string send_money_to_bank_account {
            get {
                return ResourceManager.GetString("send_money_to_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send money to kola member.
        /// </summary>
        internal static string send_money_to_kola_member {
            get {
                return ResourceManager.GetString("send_money_to_kola_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send money to peer.
        /// </summary>
        internal static string send_money_to_peer {
            get {
                return ResourceManager.GetString("send_money_to_peer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share link.
        /// </summary>
        internal static string share_link {
            get {
                return ResourceManager.GetString("share_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign up.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source account.
        /// </summary>
        internal static string source_account {
            get {
                return ResourceManager.GetString("source_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected a source account.
        /// </summary>
        internal static string source_account_error {
            get {
                return ResourceManager.GetString("source_account_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STATEMENT FOR.
        /// </summary>
        internal static string statement_for {
            get {
                return ResourceManager.GetString("statement_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TAKE PICTURE.
        /// </summary>
        internal static string take_coustomer_picture {
            get {
                return ResourceManager.GetString("take_coustomer_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taxes.
        /// </summary>
        internal static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To bank account.
        /// </summary>
        internal static string to_bank_account {
            get {
                return ResourceManager.GetString("to_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To Kola member.
        /// </summary>
        internal static string to_kola_member {
            get {
                return ResourceManager.GetString("to_kola_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To Non-Kola.
        /// </summary>
        internal static string to_non_kola {
            get {
                return ResourceManager.GetString("to_non_kola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à to receive your notifications on this device.
        /// </summary>
        internal static string to_receive_your_notifications_on_this_device {
            get {
                return ResourceManager.GetString("to_receive_your_notifications_on_this_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total to pay.
        /// </summary>
        internal static string total_to_pay {
            get {
                return ResourceManager.GetString("total_to_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfers.
        /// </summary>
        internal static string transfers {
            get {
                return ResourceManager.GetString("transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tv.
        /// </summary>
        internal static string tv {
            get {
                return ResourceManager.GetString("tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à USE.
        /// </summary>
        internal static string use {
            get {
                return ResourceManager.GetString("use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your bank account.
        /// </summary>
        internal static string use_your_bank_account {
            get {
                return ResourceManager.GetString("use_your_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use your card.
        /// </summary>
        internal static string use_your_card {
            get {
                return ResourceManager.GetString("use_your_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User not found, please enter correct user.
        /// </summary>
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your phone number.
        /// </summary>
        internal static string username_error {
            get {
                return ResourceManager.GetString("username_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number is short.
        /// </summary>
        internal static string username_is_short {
            get {
                return ResourceManager.GetString("username_is_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilities.
        /// </summary>
        internal static string utilities {
            get {
                return ResourceManager.GetString("utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VALIDATE.
        /// </summary>
        internal static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voucher number is short.
        /// </summary>
        internal static string voucher_code_is_short {
            get {
                return ResourceManager.GetString("voucher_code_is_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your voucher number.
        /// </summary>
        internal static string voucher_number_error {
            get {
                return ResourceManager.GetString("voucher_number_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter voucher number.
        /// </summary>
        internal static string voucher_step2_title {
            get {
                return ResourceManager.GetString("voucher_step2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See Qrcode Vourcher.
        /// </summary>
        internal static string vouchers_view_qrcode {
            get {
                return ResourceManager.GetString("vouchers_view_qrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vouchers.
        /// </summary>
        internal static string vourchers {
            get {
                return ResourceManager.GetString("vourchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WANT TO LOGOUT ?.
        /// </summary>
        internal static string want_to_logout {
            get {
                return ResourceManager.GetString("want_to_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water.
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How do you want to fund account ?.
        /// </summary>
        internal static string welcome_add_kash {
            get {
                return ResourceManager.GetString("welcome_add_kash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to KolaKash.
        /// </summary>
        internal static string welcome_home {
            get {
                return ResourceManager.GetString("welcome_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual payment.
        /// </summary>
        internal static string welcome_manuel_payment {
            get {
                return ResourceManager.GetString("welcome_manuel_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment request.
        /// </summary>
        internal static string welcome_qr_payment {
            get {
                return ResourceManager.GetString("welcome_qr_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Improving the way.
        /// </summary>
        internal static string welcome_text_1 {
            get {
                return ResourceManager.GetString("welcome_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you send, receive, save and pay.
        /// </summary>
        internal static string welcome_text_2 {
            get {
                return ResourceManager.GetString("welcome_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kola Voucher Wallet.
        /// </summary>
        internal static string welcome_vouvher {
            get {
                return ResourceManager.GetString("welcome_vouvher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With bank.
        /// </summary>
        internal static string with_bank {
            get {
                return ResourceManager.GetString("with_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With card.
        /// </summary>
        internal static string with_card {
            get {
                return ResourceManager.GetString("with_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à YES.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
